const ADD_TODO = "ADD_TODO";
const TOGGLE_TODO = 'TOGGLE_TODO';
const SHOW_ALL = 'SHOW_ALL';
const SHOW_ACTIVE = 'SHOW_ACTIVE';
const SHOW_COMPLETED = 'SHOW_COMPLETED';
const SET_VISIBILITY = 'SET_VISIBILITY';
const DELETE_TODO = 'DELETE_TODO';

export {
    ADD_TODO,
    TOGGLE_TODO,
    SHOW_ALL,
    SHOW_ACTIVE,
    SHOW_COMPLETED,
    SET_VISIBILITY,
    DELETE_TODO
}